// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz3op91La4JVhtB8qTqKrEOiue2H41Y4M',
    appId: '1:864118769974:web:68fd4b579c0fc752588b97',
    messagingSenderId: '864118769974',
    projectId: 'crossroads-4a1f8',
    authDomain: 'crossroads-4a1f8.firebaseapp.com',
    storageBucket: 'crossroads-4a1f8.appspot.com',
    measurementId: 'G-EGLG142NBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV01pp9zvi_OtFltqvjmAVxiNVenCOVyw',
    appId: '1:864118769974:android:2e9c02d149e6169e588b97',
    messagingSenderId: '864118769974',
    projectId: 'crossroads-4a1f8',
    storageBucket: 'crossroads-4a1f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5lfxLs0nd4FhooTENUMFmpfDcLiAA1Qk',
    appId: '1:864118769974:ios:7a50958779069258588b97',
    messagingSenderId: '864118769974',
    projectId: 'crossroads-4a1f8',
    storageBucket: 'crossroads-4a1f8.appspot.com',
    iosClientId: '864118769974-jjqjb8lap2070mas7b7n99aifv2ssc07.apps.googleusercontent.com',
    iosBundleId: 'com.example.crossroad',
  );

}